from django.core.management.base import BaseCommand
from django.urls import get_resolver

class Command(BaseCommand):
    help = "Export Django URLs to a TypeScript file"

    def handle(self, *args, **options):
        resolver = get_resolver()
        urls = []
        for pattern in resolver.url_patterns:
            # convert to string safely
            path = str(pattern.pattern)
            urls.append(path)

        with open("frontend/src/urls.ts", "w", encoding="utf-8") as f:
            f.write("// Auto-generated by export_ts_urls\n")
            f.write("export const urls = {\n")
            for u in urls:
                f.write(f'  "{u}": "{u}",\n')
            f.write("} as const;\n")

        self.stdout.write(self.style.SUCCESS("Exported URLs to frontend/src/urls.ts"))
