# Generated by Django 5.0.6 on 2025-07-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='message_number',
            field=models.IntegerField(default=0),
        ),
    ]
