# Generated by Django 5.0.6 on 2025-08-04 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_message_count_message_message_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(related_name='friends_of', to='chat.chatuser')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chatuser')),
                ('requested_users', models.ManyToManyField(related_name='requested_by', to='chat.chatuser')),
            ],
        ),
    ]
